# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9f1e434d52e2226ad09c38898f39a2d2e05768c4d9ff8c302ba5e9d151a469d1b908e79d3039395b42deab9eaf5d67c0bfa124935fe195f93af79822ef7440e

test:
  secret_key_base: 61dc0deed1ba6607850702cdd5034a436e64d988fc1d9e7a62b694ceaa2c48b012db4059ae6c974015b3b1c7d51815b7b8814c334e529b5a2bfe2f6fc1f7a65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
